import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// The sidebar is generated automatically from the folder structure under docs/.
// Category order + labels come from each folder's _category_.json.
const sidebars: SidebarsConfig = {
  guidesSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
